#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test_mem
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userAuth
#    username:
#    password:

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mail:
#    host:
#    username:
#    password:
    port: 465
    protocol: smtps
